### PR TITLE
2024 updates

### PR DESCRIPTION
**Pull request by erhmestel**
Initial set of 2024 updates for testing

### CODE REVIEW

**Comment by calum-chamberlain** [comment]
Can you update the environment.yml file please El to the one you were using (e.g. update the Python version, add nodefaults to channels and unpin pygmt).

**Comment by calum-chamberlain** [comment]
Note: to run tests locally you can run:
`pytest --nbval --sanitize-with doc_sanitize.cfg`

Before running the tests I would recommend running all the cells to make sure you get the results you expect:
`jupyter nbconvert --execute --to notebook --inplace your-notebook.ipynb`

**Comment by calum-chamberlain** [comment]
Hey El,
I'm just playing with the pinning and updating the test runner to python 3.11. I will push some changes here shortly.
C

**Comment by calum-chamberlain** [comment]
Okay, looks like tests are running. The test fails in module 3A look like they could be worked around by setting an enddate to the request to get earthquakes. 

The fail in 1B looks like the first cell wasn't run before putting it up here.

In the pygmt plotting, the colour scheme for depth isn't looking great - you might try either limiting the maximum depth of earthquakes requested, and/or inverting the colourscheme.

**Review by calum-chamberlain — CHANGES_REQUESTED** [review]
1. Run cell 1 in module 1B before pushing.
2. Limit timespan for earthquakes in 3B
3. Change depth colourscheme in pygmt plotting so that most earthquakes are not black.

**Comment by erhmestel** [comment]
Thanks, Calum. 
 
The other issue we have: unable to upload 3B because the file once run is too large (~40MB). Git is blocking anything greater than 25MB. I can upload it without the results, but that messes up the testing. Any suggestions?

First cell in 1B is the 100 / 0 deliberate error cell. The error meant the tests I ran just failed and stopped!
Earthquakes in 3A now limited 2015-01-01 to 2020-01-01 with an added note about the end date meaning we get EQs to end of 2019.
Colourscheme reversed direction with the updated pygmt version - fixed this yesterday, not pushed it yet!

Will push all these as a group once fixed!

**Comment by calum-chamberlain** [comment]
Module 3B:

It looks like the final massive seaborn figure is the issue there. Try adding the line:
```python
sns.set_theme(rc={"figure.dpi": 96})
```
in cell 33 before making the big PairGrid plot. This reduced the size of the notebook dramatically for me. You could add a comment next to that line of code explaining what it does and that they can change it to higher numbers if they want.

There are also lots of warnings in 3B with the environment that I pushed about `date_parser` being depreciated. If you are getting them as well then please correct that - the fewer warnings the better as the students often get hung up thinking they are errors (some are okay because it gets them used to differentiating between errors and warnings).

3A errors look to still be related to no enddate?

**Comment by erhmestel** [comment]
Thanks, Calum.

Yep, date_parser is depreciated, replaced by date_format. I have swapped that over in the 3B notebook I just pushed. This also meant removing your parser function and replacing just with the date format string assigned to variable parser.

I think the only warnings I am getting now are the: import pandas as pd warning about pyarrow becoming a required dependency. Pretty sure that one is okay!

3A errors - there was a second use to the function that I missed - correcting it now.

**Pull request merged**
