### PR TITLE
WIP: Work on ideas from Ash and Jessie

### PR DESCRIPTION
**Pull request by calum-chamberlain**
See #6 

This PR should cover the following:
- [x] It could be really helpful to have an example of how to plot vertical and horizontal lines in matplotlib.
- [x] It could be helpful to show an example of using a for loop and a function nested within one another. Cause I've been doing that heaps in my codes and it took me ages to figure it out.
- [x] I don't understand what classes are at all... and I'm not sure if we need to know what they are.
- [x] It would be really helpful to have an extra section which shows how to edit a dataframe. Stuff like removing/adding rows and columns, resetting the index, and loading in specific columns of a txt file. And some more examples of slicing the dataframe could be useful because we use it all the time.
- [x] Turn interactive plotting back on
- [x] Turn tag view off on all cells.

### CODE REVIEW

**Comment by calum-chamberlain** [comment]
I have added a note to make it clearer that students can skim over the classes section without trying to understand it too much.

**Comment by calum-chamberlain** [comment]
I think the only thing that I'm missing is resetting the index.

**Comment by calum-chamberlain** [comment]
@FinniganIK Would you be able to cast your eye over this - I think this is the last thing I want to do before term starts. Once we are happy we can pass Aleks the environment and start getting things set up in uni, and send info to students in prep for the year.

**Review by FinniganIK — APPROVED** [review]
Looks great, just spotted a couple of typos

**Pull request merged**
