### PR TITLE
More seaborn examples

### PR DESCRIPTION
**Pull request by FinniganIK**
Added seaborn plotting examples and a new geochemistry dataset into data

### CODE REVIEW

**Comment by calum-chamberlain** [comment]
This looks great Finn! Do you want to make sure that the correct data are loaded by re-loading the dataframe before each plot (if reading the data doesn't take too long)? I can imagine someone re-running one of the earlier plots after loading the second `geochem`data...

**Comment by calum-chamberlain** [comment]
P.S. I will fix the tests shortly - that was my doing yesterday, sorry!

**Comment by FinniganIK** [comment]
Yeah good call, I'll make that fix now

**Comment by calum-chamberlain** [comment]
Golden, thank Finn - I have got the tests passing on master as well so hopefully this goes green.

Would you be able to add an exercise or two to this? Just simple "try making this plot..." or "now get some other data and make a nice plot"?

**Comment by FinniganIK** [comment]
Couple of exercises added now

**Comment by calum-chamberlain** [comment]
Looks good to me - are you happy for me to merge this?

**Comment by FinniganIK** [comment]
Yep merge away

**Pull request merged**
